### ISSUE TITLE
Dialog Box won't close or release focus?

### ISSUE THREAD

**Issue by artwhaley** [krpc/NameTag#1]
I'm having an issue with this mod locking up KSP when I try to set a name tag in the VAB?   The problem is NOT occurring when I uninstall and install KOS and use the nametag feature there?  Running current release KSP 1.2.2.  I'll try to poke around and compare it with the KOS source to see if they've changed anything since you forked this out.

**Comment by djungelorm** [comment]
There have been some changes in the kOS repo. I've imported them over (and written a little diff script so we can easily check for changes in future). Not had a chance to check if this fixes the bug yet though.

**Comment by djungelorm** [comment]
Works for me in KSP 1.3 - although I had to manually install module manager... should probably make that a hard dependency

**Comment by artwhaley** [comment]
Awesome!   This is such a useful feature.   Instead of making it a separate mod and trying to have KOS and KRPC both depend on it, would there be a way to build it into KRPC but have that bit only load if it detects KOS is not present?    Just a thought!

**Comment by djungelorm** [comment]
Potentially. I'll have a look into this. Added a separate issue  for this here: #2
