### ISSUE TITLE
Merge into kRPC release

### ISSUE THREAD

**Issue by djungelorm** [krpc/NameTag#2]
Can this functionality be merged into the main kRPC mod, in such a way that it disables itself if kOS is also present?

**Comment by bzm3r** [comment]
Any updates on this? I don't have kOS installed, and I just want to use name tags accessible via the kRPC API. In particular, is this working for 1.4.3?

**Comment by djungelorm** [comment]
This has been merged into the main kRPC release. This mod is therefore obsolete.
